#!/bin/bash -el

# Copyright 2018 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/rc/config

curl https://sh.rustup.rs -sSf | sh -s -- -y

chown -R ${USER}:${USER} ${HOME}/.cargo ${HOME}/.rustup ${HOME}/.multirust

apt-get update
apt-get install -y --no-install-recommends build-essential
